videography: Live-Action
title: "Dream Girl"
langs:
  audio:
    - Hindi
  subtitle: []
genres:
  - Drama
  - Romance
description: >
  Karamveer gets a job at a call centre due to his ability to talk in a woman's
  voice. He garners a big fan following but soon gets in trouble with his
  overzealous clients.
cast: []
directors: []
release:
  date: 2019-09-13
  status: Released
production: Balaji Motion Pictures
duration: 0
rating:
  - 0
  - 0
  - 0
  - 0
  - 0
views: 0
