videography: Live-Action
title: "Andhadhun"
langs:
  audio:
    - Hindi
  subtitle: []
genres:
  - Comedy
  - Crime
description: >
  Akash, a piano player pretending to be visually-impaired, unwittingly becomes
  entangled in a number of problems as he witnesses the murder of a former film
  actor.
cast: []
directors: []
release:
  date: 2018-10-05
  status: Released
production: Viacom18 Studios
duration: 0
rating:
  - 0
  - 0
  - 0
  - 0
  - 0
views: 0
