videography: Live-Action
title: "Shubh Mangal Saavdhan"
langs:
  audio:
    - Hindi
  subtitle: []
genres:
  - Comedy
  - Drama
description: >
  A shy boy, Mudit, manages to woo Sugandha and the two decide to get married.
  However, before the wedding, their relationship undergoes a setback as they
  discover his erectile dysfunction.
cast: []
directors: []
release:
  date: 2017-09-01
  status: Released
production: Colour Yellow Productions
duration: 0
rating:
  - 0
  - 0
  - 0
  - 0
  - 0
views: 0
