videography: Live-Action
title: "Shubh Mangal Zyada Saavdhan"
langs:
  audio:
    - Hindi
  subtitle: []
genres:
  - Comedy
  - Drama
description: >
  Gay couple Kartik and Aman face a long and difficult road to happiness as they
  battle opposition from Aman's family. However, Kartik isn't prepared to step
  back until he marries Aman.
cast: []
directors: []
release:
  date: 2020-02-21
  status: Released
production: Unknown
duration: 0
rating:
  - 0
  - 0
  - 0
  - 0
  - 0
views: 0
