videography: Live-Action
title: "Badhaai Ho"
langs:
  audio:
    - Hindi
  subtitle: []
genres:
  - Comedy
  - Drama
description: >
  Nakul, a 25-year-old man, is shocked to discover that his mother is pregnant.
  His struggle to come to terms with the news puts his relationship with his
  girlfriend, Renee, in jeopardy.
cast: []
directors: []
release:
  date: 2018-10-18
  status: Released
production: Junglee Pictures
duration: 0
rating:
  - 0
  - 0
  - 0
  - 0
  - 0
views: 0
