videography: Live-Action
title: Made in China
langs:
  audio:
    - Hindi
  subtitle: []
genres:
  - Comedy
  - Drama
description: >
  Raghu, a failing entrepreneur, travels to China in search of new business
  opportunities. However, chaos ensues when he tries to capitalise on a dubious
  aphrodisiac.
cast: []
directors: []
release:
  date: 2019-10-25
  status: Released
production: null
duration: 131
rating:
  - 0
  - 0
  - 0
  - 0
  - 0
views: 0
