videography: Live-Action
title: "Judgementall Hai Kya"
langs:
  audio:
    - Hindi
  subtitle: []
genres:
  - Comedy
  - Dark
description: >-
  Bobby, a dubbing artist who is haunted by a childhood trauma, rents out a
  portion of her house to Keshav and Rima. However, she repeatedly stalks the
  young couple and is suspicious of Keshav.
cast: []
directors: []
release:
  date: 2019-07-26
  status: Released
production: Balaji Motion Pictures
duration: 117
rating:
  - 0
  - 0
  - 0
  - 0
  - 0
views: 0
