videography: Live-Action
title: "The Aken"
langs:
    audio:
        - Bengali
    subtitle: []
genres:
    - Comedy
    - Crime
    - Mystery
description: >
    Ekendra goes to Darjeeling for a vacation but gets embroiled in a 
    mystery of a stone Bishnu Idol and a precious stamp.
cast: []
directors: []
release:
    date: null
    status: Released
production: null
duration: 0
rating:
    - 0
    - 0
    - 0
    - 0
    - 0
views: 0
