videography: Live-Action
title: "Jayeshbhai Jordaar"
langs:
    audio:
        - Hindi
    subtitle: []
genres:
    - Comedy
    - Drama
description: >
    A timid Jayesh must defy his patriarchal family as he flees with 
    his wife to save their unborn daughter from foeticide.
cast: []
directors: []
release:
    date: null
    status: 2022-05-13
production: Yash Raj Films
duration: 0
rating:
    - 0
    - 0
    - 0
    - 0
    - 0
views: 0
