videography: "Live-Action"
title: "The Ass On Adriana"
description: >
  We are blessed here at Brazzers by getting to spend some quality time with Adriana Chechik. 
  It’s nice to chill out and kick back with such a multi-talented star like Adriana. 
  So we let her take the reins and show us exactly how she likes to have it done, starting 
  with showing us a little piece of heaven. What makes us even more excited is she’s brought 
  Keiran along to show him exactly how to treat a fine work of art like Adriana’s ass.
cast:
  - Adriana Chechik
  - Keiran Lee
release:
  date: 2017-03-04
  status: Released
production: Brazzers
channel: Pornstar Like It Big
genres: []
duration: 0
rating:
  - 0
  - 0
  - 0
  - 0
  - 0
views: 0
