videography: Live-Action
title: "Living On The Edge"
description: >
  Abigail finally is able to kick back with her vibrator, and rub one out while
  he husband is at work. When her husband's friend Johnny catches her by
  surprise, she is a more than a little annoyed to be interrupted. Johnny
  figures he can expand her sexual horizons by teaching her a little bit about
  'edging' herself to climax. He gladly demonstrates the best way to tease her
  clit, pulling back just before she reaches orgasm. Johnny swears she'll have
  the biggest 'O' of her life after he's done pounding her pussy and taking her
  to the edge.
cast:
  - Abigail Mac
  - Johnny Sins
release:
  date: 2017-09-01
  status: Released
production: Brazzers
channel: Real Wife Stories
genres:
  - Muscular
  - American
  - Shaved
  - Husband
  - Big Dick
  - Jeans
  - Tank Top
  - Medium Ass
  - Athletic
  - Petite
  - Caucasian
  - Brunette
  - Wife
  - Sandals
  - Trimmed Pussy
  - Outie Pussy
  - Big Tits
  - Enhanced
  - Sex
  - Cumshot Clean-Up
  - Facial
  - Swallow
  - Handjob
  - Masturbation
  - Slow Mo
  - Ass Licking
  - Blowjob
  - Deep Throat
  - Hair Pulling
  - Pussy Licking
  - Indoors
  - Big Tits Worship
  - Cheating
  - Couples Fantasies
  - Ballerina
  - Cowgirl
  - Doggystyle
  - Missionary
  - Pile Driving
  - Reverse Cowgirl
  - Stand And Carry
  - Sex Toys
  - Vibrator
lang: English
duration: 0
rating:
  - 0
  - 0
  - 0
  - 0
  - 0
views: 0
