videography: Live-Action
title: "Ashly Anderson Fucking In The Bedroom With Her Tits"
description: >
  Ashly Anderson has been dying to ask her friend’s brother Ryan to go with her
  to a sorority dance, and now that she finally has time alone with him, she
  musters up the courage! But the dickhead says no. His sister left to see her
  boyfriend, and all he can do to little Ashly Anderson, standing by the
  staircase, is deny her something she so dreamily desires. Well, fuck him.
  Those are the thoughts, both figuratively and literally, of Ashly. She follows
  him upstairs to his bedroom and tells him she still wants to hang out with
  him. Even when he requests she wear a particular pair of fishnet stockings to
  do so (who is this guy???). So she does. And she bends over. And Ryan rips
  open the stockings and…well, we’ll let you see for yourself whether Ashly gets
  what she ultimately wanted!
cast:
  - Ashly Anderson
  - Ryan Driller
release:
  date: 2017-09-27
  status: Released
production: Naughty America
channel: My Sister's Hot Friend
genres:
  - Blow Job
  - Brunette
  - Facial
  - Fake Tits
  - Foot Fetish
  - Medium Fake Tits
  - Medium Tits
  - My Sister's Hot Friend
  - Shaved
  - Stockings
  - Straight
lang: English
duration: 48
rating:
  - 0
  - 0
  - 0
  - 0
  - 0
views: 0
