videography: Live-Action
title: "Horny & Dangerous"
description: >
  Cock starved convict Abigail Mac is on the lam and on the hunt for a big juicy
  cock. She comes across Johnny Sins and gets all worked up watching him work on
  his car. Abigail needs a sweet release from all her pent up prison passion,
  but she's running out of time...
cast:
  - Abigail Mac
  - Johnny Sins
release:
  date: 2018-01-15
  status: Released
production: Brazzers
channel: Pornstars Like it Big
genres:
  - Muscular
  - American
  - Shaved
  - Big Dick
  - Body Suit
  - Medium Ass
  - Tattoo
  - Athletic
  - Caucasian
  - Brunette
  - Criminal
  - Prisoner
  - Trimmed Pussy
  - Outie Pussy
  - Big Tits
  - Enhanced
  - Sex
  - Cumshot Clean-Up
  - Facial
  - Swallow
  - Masturbation
  - Slow Mo
  - Voyeur
  - Ass Licking
  - Blowjob
  - Blowjob - POV
  - Hair Pulling
  - Pussy Licking
  - Spanking
  - Bathroom
  - Garage
  - Indoors
  - Outdoors
  - Shower
  - Big Tits Worship
  - "69"
  - Cowgirl
  - Doggystyle
  - Doggystyle - Standing
  - Missionary
  - Reverse Cowgirl
  - Side Fuck
lang: English
duration: 0
rating:
  - 0
  - 0
  - 0
  - 0
  - 0
views: 0
