videography: Live-Action
title: "Horny & Dangerous: Conjugal Visit"
description: >
  Cock starved convict Abigail Mac is locked up and lonely when she receives a
  love letter from Johnny Sins. Johnny professes his love for her and outlines a
  plan. If Abigail consents to marrying him, they’d be entitled to a conjugal
  visit. Abigail enthusiastically agrees and Johnny visits her in prison for
  some sultry husband and wife time under the watchful eye of Abigail’s prison
  guard.
cast:
  - Abigail Mac
  - Johnny Sins
release:
  date: 2018-03-28
  status: Released
production: Brazzers
channel: Real Wife Stories
genres:
  - Muscular
  - American
  - Shaved
  - Husband
  - Married
  - Big Dick
  - Tank Top
  - Medium Ass
  - Woman (20-29)
  - Tattoo
  - Athletic
  - Caucasian
  - Brunette
  - Prisoner
  - Wife
  - Thong
  - Trimmed Pussy
  - Outie Pussy
  - Big Tits
  - Enhanced
  - Sex
  - Cumshot Clean-Up
  - Facial
  - Masturbation
  - Ass Licking
  - Blowjob
  - Blowjob - POV
  - Deep Throat
  - Face Fuck
  - Gagging
  - Hair Pulling
  - Pussy Fingering
  - Pussy Licking
  - Spanking
  - Indoors
  - Prison
  - Big Tits Worship
  - Couples Fantasies
  - "69"
  - Ballerina
  - Cowgirl
  - Doggystyle - Standing
  - Missionary
  - Reverse Cowgirl
  - Side Fuck
  - Stand And Carry
lang: English
duration: 0
rating:
  - 0
  - 0
  - 0
  - 0
  - 0
views: 0
