videography: Live-Action
title: "Horny & Dangerous: Life On The Lam"
description: >
  Xander Corvus is trying to enjoy a quiet night out with his girlfriend when a
  shocking police report about an escaped horny inmate blares out of his car
  radio. His girlfriend is nervous, but absolutely freaks out when Abigail Mac
  pops up in in her jail uniform, pants thrown to the ground! Xander is stunned,
  but sticks around to see where this goes, his girl runs off so he’s ready to
  fuck! Back in his garage, Xander bends Abigail over his sports car and spreads
  her criminally perfect ass wide to better fill her tight pussy with all the
  hard cock it can take! Grabbing a handful of her big tits while she slobbers
  all over him is enough to send Xander over the edge, unloading all over her
  pretty face!
cast:
  - Abigail Mac
  - Xander Corvus
release:
  date: 2018-08-23
  status: Released
production: Brazzers
site: Pornstars Like it Big
genres:
  - Piercing
  - Average Body
  - American
  - Brown Hair
  - Short
  - Big Dick
  - Tank Top
  - Medium Ass
  - Woman (20-29)
  - Tattoo
  - Athletic
  - Caucasian
  - Brunette
  - Criminal
  - Trimmed Pussy
  - Outie Pussy
  - Big Tits
  - Enhanced
  - Sex
  - Cumshot Clean-Up
  - Facial
  - Masturbation
  - Voyeur
  - Anal Fingering
  - Ass Licking
  - Blowjob
  - Deep Throat
  - Face Fuck
  - Spanking
  - Titty Fuck
  - Car
  - Outdoors
  - Big Tits Worship
  - cheating
  - Couples Fantasies
  - Ballerina
  - Doggystyle - Standing
  - Missionary
  - Reverse Cowgirl
  - Side Fuck
lang: English
duration: 0
rating:
  - 0
  - 0
  - 0
  - 0
  - 0
views: 0
