videography: Live-Action
title: "Horny & Dangerous: Stolen Identity"
description: >
  After a few months on the lam, Abigail Mac has adjusted to her new domestic
  life with her unsuspecting spouse. She plays the perfect homemaker until
  bounty hunter Damon Dice tracks her down. Determined to remain a free woman,
  Abigail offers to do anything to appease Damon. Plus it’s been a while since
  she’s had a proper fuck… But will it be enough to keep her identity secret?
cast:
  - Abigail Mac
  - Damon Dice
release:
  date: 2019-03-29
  status: Released
production: Brazzers
site: Real Wife Stories
genres:
  - Skirt
  - Medium Ass
  - Woman (20-29)
  - Tattoo
  - Athletic
  - Caucasian
  - Brunette
  - High Heels
  - Boyshorts
  - Trimmed Pussy
  - Outie Pussy
  - Big Tits
  - Enhanced
  - Tattoo
  - Average Body
  - American
  - Black Hair
  - Short
  - Police
  - Average Dick
  - One-on-One
  - Couples
  - Sex
  - Cumshot Clean-Up
  - Facial
  - Fetish
  - Footjob
  - Handjob
  - Ass Licking
  - Blowjob
  - Blowjob - POV
  - Face Fuck
  - Gagging
  - Pussy Fingering
  - Pussy Licking
  - Indoors
  - Kitchen
  - Outdoors
  - cheating
  - Couples Fantasies
  - Work Fantasies
  - Ballerina
  - Cowgirl
  - Missionary
  - Reverse Cowgirl
  - Side Fuck
lang: English
duration: 0
rating:
  - 0
  - 0
  - 0
  - 0
  - 0
views: 0
